# Generated by Django 5.1.5 on 2025-01-23 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadashboard',
            old_name='user_id',
            new_name='user',
        ),
    ]
