# Generated by Django 5.1.5 on 2025-01-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_rename_user_id_datadashboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadashboard',
            name='type',
            field=models.CharField(default='framing', max_length=10),
        ),
    ]
