# Generated by Django 5.1.5 on 2025-01-24 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_datadashboard_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadashboard',
            name='type',
        ),
    ]
