# Generated by Django 5.1.5 on 2025-01-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_remove_datadashboard_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datadashboard',
            name='user',
        ),
    ]
