# Generated by Django 5.1.5 on 2025-04-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_datadashboard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='datadashboard',
            name='ref_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
