# Generated by Django 5.1.5 on 2025-04-15 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_datadashboard_ref_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadashboard',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
